name: Publish to NPM

on:
  push:
    branches: [main, master]
  pull_request:
    types: [closed]
    branches: [main, master]

permissions:
  contents: write
  packages: read

jobs:
  publish:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: demo/package-lock.json
          always-auth: true

      - name: Install dependencies
        run: |
          cd demo
          npm ci

      - name: Run type check
        run: |
          cd demo
          npm run type-check

      - name: Build package
        run: npm run build:lib

      - name: Copy built files to root
        run: |
          rm -rf ./dist
          cp -r demo/dist ./dist

      - name: Check src changes
        id: check_src
        run: |
          # Check if there are any changes in the demo/src folder
          if git diff --quiet HEAD~1 HEAD -- demo/src/ 2>/dev/null || [ ! -d "demo/src" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in demo/src folder"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in demo/src folder"
          fi

      - name: Get current version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Skip deployment notice
        if: steps.check_src.outputs.changed == 'false'
        run: |
          echo "🚫 Skipping NPM deployment - no changes detected in demo/src folder"
          echo "Only committing code changes without publishing to NPM"

      - name: Check if version exists on npm
        if: steps.check_src.outputs.changed == 'true'
        id: check_version
        run: |
          if npm view vue3-object-detection-marker@${{ steps.current_version.outputs.version }} version 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto increment version
        if: steps.check_src.outputs.changed == 'true' && steps.check_version.outputs.exists == 'true'
        run: |
          npm version patch --no-git-tag-version
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        id: new_version

      - name: Publish to NPM
        if: steps.check_src.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}

      - name: Create git tag
        if: steps.check_src.outputs.changed == 'true'
        run: |
          VERSION=${{ steps.new_version.outputs.version || steps.current_version.outputs.version }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.check_src.outputs.changed == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.new_version.outputs.version || steps.current_version.outputs.version }}
          release_name: Release v${{ steps.new_version.outputs.version || steps.current_version.outputs.version }}
          body: |
            ## Changes
            - Auto-published from ${{ github.event.head_commit.message || github.event.pull_request.title }}
            
            ## Installation
            ```bash
            npm install vue3-object-detection-marker@${{ steps.new_version.outputs.version || steps.current_version.outputs.version }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 